In [1]:
# K-Nearest Neighbors (KNN) for Obesity Classification Dataset
# 1. Setup and Data Preparation

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer

In [2]:
# 2. Load the Datasets

df = pd.read_csv('Obesity Classification.csv')

df.head()

,ID,Age,Gender,Height,Weight,BMI,Label
0,1,25,Male,175,80,25.3,Normal Weight
1,2,30,Female,160,60,22.5,Normal Weight
2,3,35,Male,180,90,27.3,Overweight
3,4,40,Female,150,50,20.0,Underweight
4,5,45,Male,190,100,31.2,Obese


In [3]:
# 3. Preprocessing and Feature Engineering
# Handling Missing Values

obesity_imputer = SimpleImputer(strategy="mean")
obesity_df_imputed = pd.DataFrame(obesity_imputer.fit_transform(df.select_dtypes(include=[np.number])))

In [4]:
# Encode Categorical Variables
# For KNN, categorical variables should be encoded into numerical values.

df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
df['Label'] = LabelEncoder().fit_transform(df['Label'])

In [5]:
# Feature Scaling
# Since KNN is sensitive to the scale of the data, we’ll apply StandardScaler to all numeric features.

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df.select_dtypes(include=[np.number]))

In [6]:
# Splitting the Data into Training and Testing Sets

# For Obesity Dataset
X_obesity = df_scaled
y_obesity = df['Label']
X_train_obesity, X_test_obesity, y_train_obesity, y_test_obesity = train_test_split(X_obesity, y_obesity, test_size=0.3, random_state=42)


In [7]:
# 4. KNN Model Construction
# Training the KNN Model
# For this, we’ll choose K=5 as a starting point, but this will be adjusted later based on hyperparameter tuning.

knn_obesity = KNeighborsClassifier(n_neighbors=5)
knn_obesity.fit(X_train_obesity, y_train_obesity)

KNeighborsClassifier()

In [8]:
# 5. Model Evaluation
# We will evaluate the models using Accuracy, Classification Report, Confusion Matrix,
# and ROC-AUC for binary classification.

y_pred_obesity = knn_obesity.predict(X_test_obesity)
print("Obesity Model Accuracy:", accuracy_score(y_test_obesity, y_pred_obesity))
print("Classification Report:\n", classification_report(y_test_obesity, y_pred_obesity))
print("Confusion Matrix:\n", confusion_matrix(y_test_obesity, y_pred_obesity))


Obesity Model Accuracy: 0.9696969696969697
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.83      1.00      0.91         5
           2       1.00      0.89      0.94         9
           3       1.00      1.00      1.00        13

    accuracy                           0.97        33
   macro avg       0.96      0.97      0.96        33
weighted avg       0.97      0.97      0.97        33

Confusion Matrix:
 [[ 6  0  0  0]
 [ 0  5  0  0]
 [ 0  1  8  0]
 [ 0  0  0 13]]


In [9]:
# 6. Hyperparameter Tuning and Model Optimization
# We will perform Grid Search for K to find the best hyperparameter.

from sklearn.model_selection import GridSearchCV

# Grid search for Obesity Dataset
param_grid = {'n_neighbors': np.arange(1, 21)}
grid_search_obesity = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)
grid_search_obesity.fit(X_train_obesity, y_train_obesity)
print(f"Best K for Obesity Dataset: {grid_search_obesity.best_params_}")


Best K for Obesity Dataset: {'n_neighbors': np.int64(1)}
